"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class BidAskProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class BidAskData(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        CODE_FIELD_NUMBER: builtins.int
        DATE_TIME_FIELD_NUMBER: builtins.int
        BID_PRICE_FIELD_NUMBER: builtins.int
        BID_VOLUME_FIELD_NUMBER: builtins.int
        DIFF_BID_VOL_FIELD_NUMBER: builtins.int
        ASK_PRICE_FIELD_NUMBER: builtins.int
        ASK_VOLUME_FIELD_NUMBER: builtins.int
        DIFF_ASK_VOL_FIELD_NUMBER: builtins.int
        SUSPEND_FIELD_NUMBER: builtins.int
        SIMTRADE_FIELD_NUMBER: builtins.int
        code: typing.Text = ...
        date_time: typing.Text = ...
        @property
        def bid_price(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
        @property
        def bid_volume(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def diff_bid_vol(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def ask_price(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
        @property
        def ask_volume(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        @property
        def diff_ask_vol(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
        suspend: builtins.int = ...
        simtrade: builtins.int = ...
        def __init__(self,
            *,
            code : typing.Text = ...,
            date_time : typing.Text = ...,
            bid_price : typing.Optional[typing.Iterable[builtins.float]] = ...,
            bid_volume : typing.Optional[typing.Iterable[builtins.int]] = ...,
            diff_bid_vol : typing.Optional[typing.Iterable[builtins.int]] = ...,
            ask_price : typing.Optional[typing.Iterable[builtins.float]] = ...,
            ask_volume : typing.Optional[typing.Iterable[builtins.int]] = ...,
            diff_ask_vol : typing.Optional[typing.Iterable[builtins.int]] = ...,
            suspend : builtins.int = ...,
            simtrade : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["ask_price",b"ask_price","ask_volume",b"ask_volume","bid_price",b"bid_price","bid_volume",b"bid_volume","code",b"code","date_time",b"date_time","diff_ask_vol",b"diff_ask_vol","diff_bid_vol",b"diff_bid_vol","simtrade",b"simtrade","suspend",b"suspend"]) -> None: ...

    EXCHANGE_FIELD_NUMBER: builtins.int
    BID_ASK_FIELD_NUMBER: builtins.int
    exchange: typing.Text = ...
    @property
    def bid_ask(self) -> global___BidAskProto.BidAskData: ...
    def __init__(self,
        *,
        exchange : typing.Text = ...,
        bid_ask : typing.Optional[global___BidAskProto.BidAskData] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bid_ask",b"bid_ask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bid_ask",b"bid_ask","exchange",b"exchange"]) -> None: ...
global___BidAskProto = BidAskProto
