# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/bidask.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#trade_bot_protobuf/src/bidask.proto\x12\x0f\x62idask_protobuf\"\xa6\x02\n\x0b\x42idAskProto\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x38\n\x07\x62id_ask\x18\x02 \x01(\x0b\x32\'.bidask_protobuf.BidAskProto.BidAskData\x1a\xca\x01\n\nBidAskData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x11\n\tdate_time\x18\x02 \x01(\t\x12\x11\n\tbid_price\x18\x03 \x03(\x01\x12\x12\n\nbid_volume\x18\x04 \x03(\x03\x12\x14\n\x0c\x64iff_bid_vol\x18\x05 \x03(\x03\x12\x11\n\task_price\x18\x06 \x03(\x01\x12\x12\n\nask_volume\x18\x07 \x03(\x03\x12\x14\n\x0c\x64iff_ask_vol\x18\x08 \x03(\x03\x12\x0f\n\x07suspend\x18\t \x01(\x03\x12\x10\n\x08simtrade\x18\n \x01(\x03\x42\x13Z\x11pkg/models/bidaskb\x06proto3')



_BIDASKPROTO = DESCRIPTOR.message_types_by_name['BidAskProto']
_BIDASKPROTO_BIDASKDATA = _BIDASKPROTO.nested_types_by_name['BidAskData']
BidAskProto = _reflection.GeneratedProtocolMessageType('BidAskProto', (_message.Message,), {

  'BidAskData' : _reflection.GeneratedProtocolMessageType('BidAskData', (_message.Message,), {
    'DESCRIPTOR' : _BIDASKPROTO_BIDASKDATA,
    '__module__' : 'trade_bot_protobuf.src.bidask_pb2'
    # @@protoc_insertion_point(class_scope:bidask_protobuf.BidAskProto.BidAskData)
    })
  ,
  'DESCRIPTOR' : _BIDASKPROTO,
  '__module__' : 'trade_bot_protobuf.src.bidask_pb2'
  # @@protoc_insertion_point(class_scope:bidask_protobuf.BidAskProto)
  })
_sym_db.RegisterMessage(BidAskProto)
_sym_db.RegisterMessage(BidAskProto.BidAskData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021pkg/models/bidask'
  _BIDASKPROTO._serialized_start=57
  _BIDASKPROTO._serialized_end=351
  _BIDASKPROTO_BIDASKDATA._serialized_start=149
  _BIDASKPROTO_BIDASKDATA._serialized_end=351
# @@protoc_insertion_point(module_scope)
