# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/bidask.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade_bot_protobuf/src/bidask.proto',
  package='bidask_protobuf',
  syntax='proto3',
  serialized_options=b'Z\021pkg/models/bidask',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#trade_bot_protobuf/src/bidask.proto\x12\x0f\x62idask_protobuf\"\xa6\x02\n\x0b\x42idAskProto\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x38\n\x07\x62id_ask\x18\x02 \x01(\x0b\x32\'.bidask_protobuf.BidAskProto.BidAskData\x1a\xca\x01\n\nBidAskData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x11\n\tdate_time\x18\x02 \x01(\t\x12\x11\n\tbid_price\x18\x03 \x03(\x01\x12\x12\n\nbid_volume\x18\x04 \x03(\x03\x12\x14\n\x0c\x64iff_bid_vol\x18\x05 \x03(\x03\x12\x11\n\task_price\x18\x06 \x03(\x01\x12\x12\n\nask_volume\x18\x07 \x03(\x03\x12\x14\n\x0c\x64iff_ask_vol\x18\x08 \x03(\x03\x12\x0f\n\x07suspend\x18\t \x01(\x03\x12\x10\n\x08simtrade\x18\n \x01(\x03\x42\x13Z\x11pkg/models/bidaskb\x06proto3'
)




_BIDASKPROTO_BIDASKDATA = _descriptor.Descriptor(
  name='BidAskData',
  full_name='bidask_protobuf.BidAskProto.BidAskData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='bidask_protobuf.BidAskProto.BidAskData.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_time', full_name='bidask_protobuf.BidAskProto.BidAskData.date_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bid_price', full_name='bidask_protobuf.BidAskProto.BidAskData.bid_price', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bid_volume', full_name='bidask_protobuf.BidAskProto.BidAskData.bid_volume', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='diff_bid_vol', full_name='bidask_protobuf.BidAskProto.BidAskData.diff_bid_vol', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ask_price', full_name='bidask_protobuf.BidAskProto.BidAskData.ask_price', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ask_volume', full_name='bidask_protobuf.BidAskProto.BidAskData.ask_volume', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='diff_ask_vol', full_name='bidask_protobuf.BidAskProto.BidAskData.diff_ask_vol', index=7,
      number=8, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='suspend', full_name='bidask_protobuf.BidAskProto.BidAskData.suspend', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simtrade', full_name='bidask_protobuf.BidAskProto.BidAskData.simtrade', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=351,
)

_BIDASKPROTO = _descriptor.Descriptor(
  name='BidAskProto',
  full_name='bidask_protobuf.BidAskProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='bidask_protobuf.BidAskProto.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bid_ask', full_name='bidask_protobuf.BidAskProto.bid_ask', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BIDASKPROTO_BIDASKDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=351,
)

_BIDASKPROTO_BIDASKDATA.containing_type = _BIDASKPROTO
_BIDASKPROTO.fields_by_name['bid_ask'].message_type = _BIDASKPROTO_BIDASKDATA
DESCRIPTOR.message_types_by_name['BidAskProto'] = _BIDASKPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BidAskProto = _reflection.GeneratedProtocolMessageType('BidAskProto', (_message.Message,), {

  'BidAskData' : _reflection.GeneratedProtocolMessageType('BidAskData', (_message.Message,), {
    'DESCRIPTOR' : _BIDASKPROTO_BIDASKDATA,
    '__module__' : 'trade_bot_protobuf.src.bidask_pb2'
    # @@protoc_insertion_point(class_scope:bidask_protobuf.BidAskProto.BidAskData)
    })
  ,
  'DESCRIPTOR' : _BIDASKPROTO,
  '__module__' : 'trade_bot_protobuf.src.bidask_pb2'
  # @@protoc_insertion_point(class_scope:bidask_protobuf.BidAskProto)
  })
_sym_db.RegisterMessage(BidAskProto)
_sym_db.RegisterMessage(BidAskProto.BidAskData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
