"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class EntireTickArrProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntireTickProto]: ...
    def __init__(self,
        *,
        data : typing.Optional[typing.Iterable[global___EntireTickProto]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"data",b"data"]) -> None: ...
global___EntireTickArrProto = EntireTickArrProto

class EntireTickProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TS_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    BID_PRICE_FIELD_NUMBER: builtins.int
    BID_VOLUME_FIELD_NUMBER: builtins.int
    ASK_PRICE_FIELD_NUMBER: builtins.int
    ASK_VOLUME_FIELD_NUMBER: builtins.int
    ts: builtins.int = ...
    close: builtins.float = ...
    volume: builtins.int = ...
    bid_price: builtins.float = ...
    bid_volume: builtins.int = ...
    ask_price: builtins.float = ...
    ask_volume: builtins.int = ...
    def __init__(self,
        *,
        ts : builtins.int = ...,
        close : builtins.float = ...,
        volume : builtins.int = ...,
        bid_price : builtins.float = ...,
        bid_volume : builtins.int = ...,
        ask_price : builtins.float = ...,
        ask_volume : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ask_price",b"ask_price",u"ask_volume",b"ask_volume",u"bid_price",b"bid_price",u"bid_volume",b"bid_volume",u"close",b"close",u"ts",b"ts",u"volume",b"volume"]) -> None: ...
global___EntireTickProto = EntireTickProto
