# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/entiretick.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'trade_bot_protobuf/src/entiretick.proto\x12\x13\x65ntiretick_protobuf\"H\n\x12\x45ntireTickArrProto\x12\x32\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32$.entiretick_protobuf.EntireTickProto\"\x8a\x01\n\x0f\x45ntireTickProto\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\r\n\x05\x63lose\x18\x02 \x01(\x01\x12\x0e\n\x06volume\x18\x03 \x01(\x03\x12\x11\n\tbid_price\x18\x04 \x01(\x01\x12\x12\n\nbid_volume\x18\x05 \x01(\x03\x12\x11\n\task_price\x18\x06 \x01(\x01\x12\x12\n\nask_volume\x18\x07 \x01(\x03\x42\x17Z\x15pkg/models/entiretickb\x06proto3')



_ENTIRETICKARRPROTO = DESCRIPTOR.message_types_by_name['EntireTickArrProto']
_ENTIRETICKPROTO = DESCRIPTOR.message_types_by_name['EntireTickProto']
EntireTickArrProto = _reflection.GeneratedProtocolMessageType('EntireTickArrProto', (_message.Message,), {
  'DESCRIPTOR' : _ENTIRETICKARRPROTO,
  '__module__' : 'trade_bot_protobuf.src.entiretick_pb2'
  # @@protoc_insertion_point(class_scope:entiretick_protobuf.EntireTickArrProto)
  })
_sym_db.RegisterMessage(EntireTickArrProto)

EntireTickProto = _reflection.GeneratedProtocolMessageType('EntireTickProto', (_message.Message,), {
  'DESCRIPTOR' : _ENTIRETICKPROTO,
  '__module__' : 'trade_bot_protobuf.src.entiretick_pb2'
  # @@protoc_insertion_point(class_scope:entiretick_protobuf.EntireTickProto)
  })
_sym_db.RegisterMessage(EntireTickProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025pkg/models/entiretick'
  _ENTIRETICKARRPROTO._serialized_start=64
  _ENTIRETICKARRPROTO._serialized_end=136
  _ENTIRETICKPROTO._serialized_start=139
  _ENTIRETICKPROTO._serialized_end=277
# @@protoc_insertion_point(module_scope)
