# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/kbar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade_bot_protobuf/src/kbar.proto',
  package='kbar_protobuf',
  syntax='proto3',
  serialized_options=b'Z\017pkg/models/kbar',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!trade_bot_protobuf/src/kbar.proto\x12\rkbar_protobuf\"6\n\x0cKbarArrProto\x12&\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x18.kbar_protobuf.KbarProto\"_\n\tKbarProto\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\r\n\x05\x43lose\x18\x02 \x01(\x01\x12\x0c\n\x04Open\x18\x03 \x01(\x01\x12\x0c\n\x04High\x18\x04 \x01(\x01\x12\x0b\n\x03Low\x18\x05 \x01(\x01\x12\x0e\n\x06Volume\x18\x06 \x01(\x03\x42\x11Z\x0fpkg/models/kbarb\x06proto3'
)




_KBARARRPROTO = _descriptor.Descriptor(
  name='KbarArrProto',
  full_name='kbar_protobuf.KbarArrProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='kbar_protobuf.KbarArrProto.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=106,
)


_KBARPROTO = _descriptor.Descriptor(
  name='KbarProto',
  full_name='kbar_protobuf.KbarProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='kbar_protobuf.KbarProto.ts', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Close', full_name='kbar_protobuf.KbarProto.Close', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Open', full_name='kbar_protobuf.KbarProto.Open', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='High', full_name='kbar_protobuf.KbarProto.High', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Low', full_name='kbar_protobuf.KbarProto.Low', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Volume', full_name='kbar_protobuf.KbarProto.Volume', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=203,
)

_KBARARRPROTO.fields_by_name['data'].message_type = _KBARPROTO
DESCRIPTOR.message_types_by_name['KbarArrProto'] = _KBARARRPROTO
DESCRIPTOR.message_types_by_name['KbarProto'] = _KBARPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KbarArrProto = _reflection.GeneratedProtocolMessageType('KbarArrProto', (_message.Message,), {
  'DESCRIPTOR' : _KBARARRPROTO,
  '__module__' : 'trade_bot_protobuf.src.kbar_pb2'
  # @@protoc_insertion_point(class_scope:kbar_protobuf.KbarArrProto)
  })
_sym_db.RegisterMessage(KbarArrProto)

KbarProto = _reflection.GeneratedProtocolMessageType('KbarProto', (_message.Message,), {
  'DESCRIPTOR' : _KBARPROTO,
  '__module__' : 'trade_bot_protobuf.src.kbar_pb2'
  # @@protoc_insertion_point(class_scope:kbar_protobuf.KbarProto)
  })
_sym_db.RegisterMessage(KbarProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
