# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/kbar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!trade_bot_protobuf/src/kbar.proto\x12\rkbar_protobuf\"6\n\x0cKbarArrProto\x12&\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x18.kbar_protobuf.KbarProto\"_\n\tKbarProto\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\r\n\x05\x43lose\x18\x02 \x01(\x01\x12\x0c\n\x04Open\x18\x03 \x01(\x01\x12\x0c\n\x04High\x18\x04 \x01(\x01\x12\x0b\n\x03Low\x18\x05 \x01(\x01\x12\x0e\n\x06Volume\x18\x06 \x01(\x03\x42\x11Z\x0fpkg/models/kbarb\x06proto3')



_KBARARRPROTO = DESCRIPTOR.message_types_by_name['KbarArrProto']
_KBARPROTO = DESCRIPTOR.message_types_by_name['KbarProto']
KbarArrProto = _reflection.GeneratedProtocolMessageType('KbarArrProto', (_message.Message,), {
  'DESCRIPTOR' : _KBARARRPROTO,
  '__module__' : 'trade_bot_protobuf.src.kbar_pb2'
  # @@protoc_insertion_point(class_scope:kbar_protobuf.KbarArrProto)
  })
_sym_db.RegisterMessage(KbarArrProto)

KbarProto = _reflection.GeneratedProtocolMessageType('KbarProto', (_message.Message,), {
  'DESCRIPTOR' : _KBARPROTO,
  '__module__' : 'trade_bot_protobuf.src.kbar_pb2'
  # @@protoc_insertion_point(class_scope:kbar_protobuf.KbarProto)
  })
_sym_db.RegisterMessage(KbarProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017pkg/models/kbar'
  _KBARARRPROTO._serialized_start=52
  _KBARARRPROTO._serialized_end=106
  _KBARPROTO._serialized_start=108
  _KBARPROTO._serialized_end=203
# @@protoc_insertion_point(module_scope)
