"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class KbarArrProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___KbarProto]: ...
    def __init__(self,
        *,
        data : typing.Optional[typing.Iterable[global___KbarProto]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data"]) -> None: ...
global___KbarArrProto = KbarArrProto

class KbarProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TS_FIELD_NUMBER: builtins.int
    CLOSE_FIELD_NUMBER: builtins.int
    OPEN_FIELD_NUMBER: builtins.int
    HIGH_FIELD_NUMBER: builtins.int
    LOW_FIELD_NUMBER: builtins.int
    VOLUME_FIELD_NUMBER: builtins.int
    ts: builtins.int = ...
    Close: builtins.float = ...
    Open: builtins.float = ...
    High: builtins.float = ...
    Low: builtins.float = ...
    Volume: builtins.int = ...
    def __init__(self,
        *,
        ts : builtins.int = ...,
        Close : builtins.float = ...,
        Open : builtins.float = ...,
        High : builtins.float = ...,
        Low : builtins.float = ...,
        Volume : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["Close",b"Close","High",b"High","Low",b"Low","Open",b"Open","Volume",b"Volume","ts",b"ts"]) -> None: ...
global___KbarProto = KbarProto
