# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/snapshot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%trade_bot_protobuf/src/snapshot.proto\x12\x11snapshot_protobuf\"B\n\x10SnapShotArrProto\x12.\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32 .snapshot_protobuf.SnapShotProto\"\xa9\x03\n\rSnapShotProto\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x10\n\x08\x65xchange\x18\x03 \x01(\t\x12\x0c\n\x04open\x18\x04 \x01(\x01\x12\x0c\n\x04high\x18\x05 \x01(\x01\x12\x0b\n\x03low\x18\x06 \x01(\x01\x12\r\n\x05\x63lose\x18\x07 \x01(\x01\x12\x11\n\ttick_type\x18\x08 \x01(\t\x12\x14\n\x0c\x63hange_price\x18\t \x01(\x01\x12\x13\n\x0b\x63hange_rate\x18\n \x01(\x01\x12\x13\n\x0b\x63hange_type\x18\x0b \x01(\t\x12\x15\n\raverage_price\x18\x0c \x01(\x01\x12\x0e\n\x06volume\x18\r \x01(\x03\x12\x14\n\x0ctotal_volume\x18\x0e \x01(\x03\x12\x0e\n\x06\x61mount\x18\x0f \x01(\x03\x12\x14\n\x0ctotal_amount\x18\x10 \x01(\x03\x12\x18\n\x10yesterday_volume\x18\x11 \x01(\x01\x12\x11\n\tbuy_price\x18\x12 \x01(\x01\x12\x12\n\nbuy_volume\x18\x13 \x01(\x01\x12\x12\n\nsell_price\x18\x14 \x01(\x01\x12\x13\n\x0bsell_volume\x18\x15 \x01(\x03\x12\x14\n\x0cvolume_ratio\x18\x16 \x01(\x01\x42\x15Z\x13pkg/models/snapshotb\x06proto3')



_SNAPSHOTARRPROTO = DESCRIPTOR.message_types_by_name['SnapShotArrProto']
_SNAPSHOTPROTO = DESCRIPTOR.message_types_by_name['SnapShotProto']
SnapShotArrProto = _reflection.GeneratedProtocolMessageType('SnapShotArrProto', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTARRPROTO,
  '__module__' : 'trade_bot_protobuf.src.snapshot_pb2'
  # @@protoc_insertion_point(class_scope:snapshot_protobuf.SnapShotArrProto)
  })
_sym_db.RegisterMessage(SnapShotArrProto)

SnapShotProto = _reflection.GeneratedProtocolMessageType('SnapShotProto', (_message.Message,), {
  'DESCRIPTOR' : _SNAPSHOTPROTO,
  '__module__' : 'trade_bot_protobuf.src.snapshot_pb2'
  # @@protoc_insertion_point(class_scope:snapshot_protobuf.SnapShotProto)
  })
_sym_db.RegisterMessage(SnapShotProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023pkg/models/snapshot'
  _SNAPSHOTARRPROTO._serialized_start=60
  _SNAPSHOTARRPROTO._serialized_end=126
  _SNAPSHOTPROTO._serialized_start=129
  _SNAPSHOTPROTO._serialized_end=554
# @@protoc_insertion_point(module_scope)
