# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/streamtick.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'trade_bot_protobuf/src/streamtick.proto\x12\x13streamtick_protobuf\"\x81\x04\n\x0fStreamTickProto\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12;\n\x04tick\x18\x02 \x01(\x0b\x32-.streamtick_protobuf.StreamTickProto.TickData\x1a\x9e\x03\n\x08TickData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x11\n\tdate_time\x18\x02 \x01(\t\x12\x0c\n\x04open\x18\x03 \x01(\x01\x12\x11\n\tavg_price\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0c\n\x04high\x18\x06 \x01(\x01\x12\x0b\n\x03low\x18\x07 \x01(\x01\x12\x0e\n\x06\x61mount\x18\x08 \x01(\x01\x12\x14\n\x0ctotal_amount\x18\t \x01(\x01\x12\x0e\n\x06volume\x18\n \x01(\x03\x12\x14\n\x0ctotal_volume\x18\x0b \x01(\x03\x12\x11\n\ttick_type\x18\x0c \x01(\x03\x12\x10\n\x08\x63hg_type\x18\r \x01(\x03\x12\x11\n\tprice_chg\x18\x0e \x01(\x01\x12\x0f\n\x07pct_chg\x18\x0f \x01(\x01\x12\x1a\n\x12\x62id_side_total_vol\x18\x10 \x01(\x03\x12\x1a\n\x12\x61sk_side_total_vol\x18\x11 \x01(\x03\x12\x1a\n\x12\x62id_side_total_cnt\x18\x12 \x01(\x03\x12\x1a\n\x12\x61sk_side_total_cnt\x18\x13 \x01(\x03\x12\x0f\n\x07suspend\x18\x14 \x01(\x03\x12\x10\n\x08simtrade\x18\x15 \x01(\x03\x42\x17Z\x15pkg/models/streamtickb\x06proto3')



_STREAMTICKPROTO = DESCRIPTOR.message_types_by_name['StreamTickProto']
_STREAMTICKPROTO_TICKDATA = _STREAMTICKPROTO.nested_types_by_name['TickData']
StreamTickProto = _reflection.GeneratedProtocolMessageType('StreamTickProto', (_message.Message,), {

  'TickData' : _reflection.GeneratedProtocolMessageType('TickData', (_message.Message,), {
    'DESCRIPTOR' : _STREAMTICKPROTO_TICKDATA,
    '__module__' : 'trade_bot_protobuf.src.streamtick_pb2'
    # @@protoc_insertion_point(class_scope:streamtick_protobuf.StreamTickProto.TickData)
    })
  ,
  'DESCRIPTOR' : _STREAMTICKPROTO,
  '__module__' : 'trade_bot_protobuf.src.streamtick_pb2'
  # @@protoc_insertion_point(class_scope:streamtick_protobuf.StreamTickProto)
  })
_sym_db.RegisterMessage(StreamTickProto)
_sym_db.RegisterMessage(StreamTickProto.TickData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025pkg/models/streamtick'
  _STREAMTICKPROTO._serialized_start=65
  _STREAMTICKPROTO._serialized_end=578
  _STREAMTICKPROTO_TICKDATA._serialized_start=164
  _STREAMTICKPROTO_TICKDATA._serialized_end=578
# @@protoc_insertion_point(module_scope)
