"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class EventProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESP_CODE_FIELD_NUMBER: builtins.int
    EVENT_CODE_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    resp_code: builtins.int = ...
    event_code: builtins.int = ...
    info: typing.Text = ...
    event: typing.Text = ...
    def __init__(self,
        *,
        resp_code : builtins.int = ...,
        event_code : builtins.int = ...,
        info : typing.Text = ...,
        event : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"event",b"event",u"event_code",b"event_code",u"info",b"info",u"resp_code",b"resp_code"]) -> None: ...
global___EventProto = EventProto
