# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/traderecord.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(trade_bot_protobuf/src/traderecord.proto\x12\x15trade_record_protobuf\"L\n\x13TradeRecordArrProto\x12\x35\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\'.trade_record_protobuf.TradeRecordProto\"\x81\x01\n\x10TradeRecordProto\x12\x10\n\x08quantity\x18\x01 \x01(\x03\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\n\n\x02id\x18\x05 \x01(\t\x12\x12\n\norder_time\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\tB\x18Z\x16pkg/models/traderecordb\x06proto3')



_TRADERECORDARRPROTO = DESCRIPTOR.message_types_by_name['TradeRecordArrProto']
_TRADERECORDPROTO = DESCRIPTOR.message_types_by_name['TradeRecordProto']
TradeRecordArrProto = _reflection.GeneratedProtocolMessageType('TradeRecordArrProto', (_message.Message,), {
  'DESCRIPTOR' : _TRADERECORDARRPROTO,
  '__module__' : 'trade_bot_protobuf.src.traderecord_pb2'
  # @@protoc_insertion_point(class_scope:trade_record_protobuf.TradeRecordArrProto)
  })
_sym_db.RegisterMessage(TradeRecordArrProto)

TradeRecordProto = _reflection.GeneratedProtocolMessageType('TradeRecordProto', (_message.Message,), {
  'DESCRIPTOR' : _TRADERECORDPROTO,
  '__module__' : 'trade_bot_protobuf.src.traderecord_pb2'
  # @@protoc_insertion_point(class_scope:trade_record_protobuf.TradeRecordProto)
  })
_sym_db.RegisterMessage(TradeRecordProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026pkg/models/traderecord'
  _TRADERECORDARRPROTO._serialized_start=67
  _TRADERECORDARRPROTO._serialized_end=143
  _TRADERECORDPROTO._serialized_start=146
  _TRADERECORDPROTO._serialized_end=275
# @@protoc_insertion_point(module_scope)
