"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TradeRecordArrProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TradeRecordProto]: ...
    def __init__(self,
        *,
        data : typing.Optional[typing.Iterable[global___TradeRecordProto]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data"]) -> None: ...
global___TradeRecordArrProto = TradeRecordArrProto

class TradeRecordProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    QUANTITY_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    ORDER_TIME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    quantity: builtins.int = ...
    price: builtins.float = ...
    action: typing.Text = ...
    code: typing.Text = ...
    id: typing.Text = ...
    order_time: typing.Text = ...
    status: typing.Text = ...
    def __init__(self,
        *,
        quantity : builtins.int = ...,
        price : builtins.float = ...,
        action : typing.Text = ...,
        code : typing.Text = ...,
        id : typing.Text = ...,
        order_time : typing.Text = ...,
        status : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["action",b"action","code",b"code","id",b"id","order_time",b"order_time","price",b"price","quantity",b"quantity","status",b"status"]) -> None: ...
global___TradeRecordProto = TradeRecordProto
