# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/tradeevent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'trade_bot_protobuf/src/tradeevent.proto\x12\x14trade_event_protobuf\"P\n\nEventProto\x12\x11\n\tresp_code\x18\x01 \x01(\x03\x12\x12\n\nevent_code\x18\x02 \x01(\x03\x12\x0c\n\x04info\x18\x03 \x01(\t\x12\r\n\x05\x65vent\x18\x04 \x01(\tB\x17Z\x15pkg/models/tradeeventb\x06proto3')



_EVENTPROTO = DESCRIPTOR.message_types_by_name['EventProto']
EventProto = _reflection.GeneratedProtocolMessageType('EventProto', (_message.Message,), {
  'DESCRIPTOR' : _EVENTPROTO,
  '__module__' : 'trade_bot_protobuf.src.tradeevent_pb2'
  # @@protoc_insertion_point(class_scope:trade_event_protobuf.EventProto)
  })
_sym_db.RegisterMessage(EventProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025pkg/models/tradeevent'
  _EVENTPROTO._serialized_start=65
  _EVENTPROTO._serialized_end=145
# @@protoc_insertion_point(module_scope)
