# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_bot_protobuf/src/volumerank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'trade_bot_protobuf/src/volumerank.proto\x12\x14volume_rank_protobuf\"I\n\x12VolumeRankArrProto\x12\x33\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32%.volume_rank_protobuf.VolumeRankProto\"\x87\x04\n\x0fVolumeRankProto\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\n\n\x02ts\x18\x04 \x01(\x03\x12\x0c\n\x04open\x18\x05 \x01(\x01\x12\x0c\n\x04high\x18\x06 \x01(\x01\x12\x0b\n\x03low\x18\x07 \x01(\x01\x12\r\n\x05\x63lose\x18\x08 \x01(\x01\x12\x13\n\x0bprice_range\x18\t \x01(\x01\x12\x11\n\ttick_type\x18\n \x01(\x03\x12\x14\n\x0c\x63hange_price\x18\x0b \x01(\x01\x12\x13\n\x0b\x63hange_type\x18\x0c \x01(\x03\x12\x15\n\raverage_price\x18\r \x01(\x01\x12\x0e\n\x06volume\x18\x0e \x01(\x03\x12\x14\n\x0ctotal_volume\x18\x0f \x01(\x03\x12\x0e\n\x06\x61mount\x18\x10 \x01(\x03\x12\x14\n\x0ctotal_amount\x18\x11 \x01(\x03\x12\x18\n\x10yesterday_volume\x18\x12 \x01(\x03\x12\x14\n\x0cvolume_ratio\x18\x13 \x01(\x01\x12\x11\n\tbuy_price\x18\x14 \x01(\x01\x12\x12\n\nbuy_volume\x18\x15 \x01(\x03\x12\x12\n\nsell_price\x18\x16 \x01(\x01\x12\x13\n\x0bsell_volume\x18\x17 \x01(\x03\x12\x12\n\nbid_orders\x18\x18 \x01(\x03\x12\x13\n\x0b\x62id_volumes\x18\x19 \x01(\x03\x12\x12\n\nask_orders\x18\x1a \x01(\x03\x12\x13\n\x0b\x61sk_volumes\x18\x1b \x01(\x03\x42\x17Z\x15pkg/models/volumerankb\x06proto3')



_VOLUMERANKARRPROTO = DESCRIPTOR.message_types_by_name['VolumeRankArrProto']
_VOLUMERANKPROTO = DESCRIPTOR.message_types_by_name['VolumeRankProto']
VolumeRankArrProto = _reflection.GeneratedProtocolMessageType('VolumeRankArrProto', (_message.Message,), {
  'DESCRIPTOR' : _VOLUMERANKARRPROTO,
  '__module__' : 'trade_bot_protobuf.src.volumerank_pb2'
  # @@protoc_insertion_point(class_scope:volume_rank_protobuf.VolumeRankArrProto)
  })
_sym_db.RegisterMessage(VolumeRankArrProto)

VolumeRankProto = _reflection.GeneratedProtocolMessageType('VolumeRankProto', (_message.Message,), {
  'DESCRIPTOR' : _VOLUMERANKPROTO,
  '__module__' : 'trade_bot_protobuf.src.volumerank_pb2'
  # @@protoc_insertion_point(class_scope:volume_rank_protobuf.VolumeRankProto)
  })
_sym_db.RegisterMessage(VolumeRankProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\025pkg/models/volumerank'
  _VOLUMERANKARRPROTO._serialized_start=65
  _VOLUMERANKARRPROTO._serialized_end=138
  _VOLUMERANKPROTO._serialized_start=141
  _VOLUMERANKPROTO._serialized_end=660
# @@protoc_insertion_point(module_scope)
